server:
  port: 9000

spring:
  cloud:
    stream:
      bindings:
        input: positions
        input.group: hdfsWrite
        input.content-type: application/json
  application:
    name: filter

filter:
  configuration:
    file:
      directory: "classpath*:/filters/*.yaml"